### ISSUE TITLE
Pepper build suggestion

### ISSUE THREAD

**Issue by ilionic** [BelaPlatform/bela-pepper#1]
Recently finished the build but got step 11. wrong - attaching LED bar graph upside down. 
That was quite challenging component to desolder and replace ( ended up ordering new one ). 
Perhaps worth adding a note for beginners like me to make sure LED bar graph text and cut corner should be facing downwards.
Thanks

**Comment by giuliomoro** [comment]
@roberthjack ?

**Comment by roberthjack** [comment]
Closed #1.

**Comment by armandhammer** [comment]
> That was quite challenging component to desolder and replace ( ended up ordering new one ).

I recently got a Hakko FR-301 desoldering gun and it has been a lifesaver. I thought I'd rarely use it, but it has paid for itself in less than a month. Highly recommended... I can't believe I went so long without one.

**Comment by ilionic** [comment]
> I recently got a Hakko FR-301 desoldering gun and it has been a lifesaver. I thought I'd rarely use it, but it has paid for itself in less than a month. Highly recommended... I can't believe I went so long without one.

Nice one, I am pretty sure Hakko doing great job here but need to justify such investment if you are desoldering lots of multi pin components.
