### ISSUE TITLE
USB connection using breakout panel

### ISSUE THREAD

**Issue by vsandstrom** [BelaPlatform/bela-pepper#4]
In the build kit there is the panel for usb host and device. I thought there would be some easy access solder points or some pins that can be configured as usb on the beaglebone, but I cannot find that info anywhere. 

I haven't found any documentation of how to install these ports either, and I am wondering if there is a method or if it is supposed to just be some kind of extension cables. 

Anyway, would mean a lot easier access to programming the device when implemented rather than inserting it removing it from the case every time you need to debug a new patch.

**Comment by roberthjack** [comment]
There are no solder points as such rather we use standard USB panel mount extension cables with a right angle connector for the board. There are some links as part of the build guide with recommended parts for both the host and device. You can find them here: https://github.com/BelaPlatform/bela-pepper/wiki/Bill-of-Materials#usb-breakout

There are a few different suppliers depending on where you are based. Hope that helps.
