### ISSUE TITLE
RK09L1140A5P Potentiometer is Discontinued

### ISSUE THREAD

**Issue by ip2k** [BelaPlatform/bela-pepper#5]
Mouser has this listed as `Obsolete` now and couldn't complete my order (Mouser cannot back-order them as they said they're discontinued, so I had to source them from Arrow who still has some left, albeit at very high shipping cost from Japan). Mouser support said there was no direct substitute, but I'm hoping that something else would be suitable and the BOM could be updated to reflect that https://github.com/BelaPlatform/bela-pepper/wiki/Bill-of-Materials .

Thanks all and awesome project, can't wait to get everything together to build mine! Mouser has been working on the parts order for me for a few months now trying to get it all together. If a kit were available for sale with all the necessary parts, that might be a nice way for less experienced builders to get going with this :)

**Comment by roberthjack** [comment]
I hope you have been able to find an appropriate replacement part. For your info we are now selling full DIY kits with all the necessary parts: https://shop.bela.io/collections/modular/products/pepper-full-diy-kit
