### ISSUE TITLE
Digital In/Out documentation

### ISSUE THREAD

**Issue by vsandstrom** [BelaPlatform/bela-pepper#8]
I am trying to find somewhere where the segment display and the buttons have their inputs/outputs documented. I am going through the DSP C++ coursework on YouTube and have difficulty using the digital I/O because nothing seems to correspond to what I think it does. 

Is there an official documentation of Pepper-specific mapping of digital I/O?

**Comment by giuliomoro** [comment]
the pinout of those pins can be found [here](https://github.com/BelaPlatform/bela-pepper/wiki/Pin-numbering)
